### PR TITLE
Use ICONS for Pokemon

### LINKED ISSUE #17: Support ICONS pokemon

### PR DESCRIPTION
**Pull request by Mygod**
Fix #17.

Needs testing.

### CODE REVIEW

**Comment by hunch-13** [comment]
sub pages such as shiny rates seem good BUT main page appears broken for top 10 (lifetime, today , and gym)

**Comment by Mygod** [comment]
@hunch-13 Thanks for testing! Pull again?

**Comment by hunch-13** [comment]
appears to be working now, issues are resolved

**Comment by hunch-13** [comment]
currently doesn't support eggs (or perhaps the url is just not included/known)

**Comment by versx** [comment]
> currently doesn't support eggs (or perhaps the url is just not included/known)

🤔 It's expecting 1-6.png
image

**Comment by hunch-13** [comment]
eggs doesn't seem to support ICONS with this PR, if you adjust the url to match pokemon it'll show 1.png and display a nice bulbasaur , of course you can use local icons but that would defeat the purpose of this PR

**Comment by versx** [comment]
> eggs doesn't seem to support ICONS with this PR, if you adjust the url to match pokemon it'll show 1.png and display a nice bulbasaur , of course you can use local icons but that would defeat the purpose of this PR

Not sure what you mean. Pokemon use ICONS format, eggs are undecided still and still use the 1-6.png format.
Also the ICONS url only has Pokemon images.

**Review by clburlison — APPROVED** [review]
works as intended

**Comment by versx** [comment]
`npn run test-fix`

**Pull request merged**
