### PR TITLE
Show top Pokemon percentages and top 20 instead of top 10

### PR DESCRIPTION
**Pull request by Anna-28**
It is handy to see what % of total spawns a specific Pokemon is. And top 20 gives a wider variety than top 10.

### CODE REVIEW

**Review by TurtIeSocks — APPROVED** [review]
Works as expected 👍

**Comment by versx** [comment]
@Anna-28 Looks good, any thoughts about making this configurable via the config?

**Comment by Anna-28** [comment]
Could make it configurable, where would the config value be located? And would it allow people to set it to top 100 for example or should it have an upper limit?

Do you mean the % shown as a config setting also?

**Comment by versx** [comment]
> Could make it configurable, where would the config value be located? And would it allow people to set it to top 100 for example or should it have an upper limit?
> 
> Do you mean the % shown as a config setting also?

I submitted a PR to your repo if you're happy with the changes, not much work but it gets it done. I'm perfectly fine with your current changes as well. It's not checking an upper limit of the variable, pretty much the Admins responsibility to set it to a reasonable number but it could be added of course. Might be worth changing the `top20`s to just `top` to prevent confusion but honestly aesthetics imo.

https://github.com/Anna-28/RDMopole2/pull/1

**Pull request merged**
