### PR TITLE
Spawnpoints map

### PR DESCRIPTION
**Pull request by versx**

### CODE REVIEW

**Review by clburlison — APPROVED** [review]
While this works I wouldn't be upset it you deleted without merging. Having this in MapJS means you only have to maintain it in one place. Additionally this currently has zero toggles around visible spawnpoints.

**Comment by Mygod** [comment]
Maybe instead we can show heatmap for all pokemon?

Also the default scale could easily freeze the browser.

**Comment by TurtIeSocks** [comment]
image

I don't share spawnpoint info with users so my feelings are biased. Everything seems to work without issue though. It does seem a little redundant though with MapJS. Would prefer biome analyzing 👀

**Comment by bschultz** [comment]
I also don't see a need for this as it's already in MapJS.

Didn't tested it though, but if this should be merged the locales would need an update first.

**Comment by versx** [comment]
The original idea was to have stats about spawnpoints within view but I'm too busy and could care less anymore. If someone wants to do more with it, feel free.

> Maybe instead we can show heatmap for all pokemon?
> 
> Also the default scale could easily freeze the browser.

There's already a heatmap for Pokemon

**Comment by Mygod** [comment]
Yes but not for all Pokemon.

**Comment by versx** [comment]
> Yes but not for all Pokemon.

Why would you want a heatmap to show all Pokemon? The reason for a heatmap is to see where a specific Pokemon spawns more in a biome. Showing everything would just be a cluster fuck and hard to view/differentiate.

**Comment by Mygod** [comment]
Useful for community day?

**Pull request closed without merging**
